Add AllWasmCodeID query
strangelove-ventures/ibc-go pull request #24
Opened 2023-03-21 19:16 UTC by vuong177

## Description
Currently, the  `codeID`  is a bit hard to track, we can only find `codeID` by querying `MsgPushNewWasmCode` transaction.
This PR is for adding a new `AllWasmCodeIDs` querier to query all codeID of contracts in the 08-wasm state.

2023-03-22 22:54 UTC, misko9 requested changes
Thanks for the PR! Let me know if you have any questions on the comments!

2023-03-22 22:54 UTC, misko9 commented on modules/light-clients/08-wasm/keeper/msg_server.go
Unfortunately, this is necessary and a few months ago, became a requirement for contract uploads to be restricted to governance proposals due to their sensitive access in ibc-go.

2023-03-22 22:54 UTC, misko9 commented on go.mod
> +require (
nit, can this be in the same require block as the other indirects?

2023-03-22 22:54 UTC, misko9 commented on modules/light-clients/08-wasm/client/cli/query.go
> +			pageReq, err := client.ReadPageRequest(cmd.Flags())
What are the flags for pagination? I don't see them in the cli help.

2023-03-23 08:38 UTC, vuong177 commented on modules/light-clients/08-wasm/types/validation.go
> +var MaxWasmSize = 16 * 1024 * 1024
@misko how do you compile the grandpa contract? I've tried to compile the composable grandpa contract but the contract size still 1.6mb?

2023-03-23 09:23 UTC, vuong177 commented on modules/light-clients/08-wasm/client/cli/query.go
> +			pageReq, err := client.ReadPageRequest(cmd.Flags())
Added in newest commit. I forget to add this flag.

2023-03-23 09:29 UTC, vuong177 commented
@misko9 thanks for reviewing.

2023-03-23 23:45 UTC, misko9 approved these changes
LGTM!

2023-03-23 23:47 UTC, merged