08-wasm: testing improvements
strangelove-ventures/ibc-go pull request #30
Opened 2023-05-16 10:48 UTC by crodriguezvega

## Description

Another large PR, so apologies for that... 😓

closes: #XXXX

### Commit Message / Changelog Entry

```bash
type: commit message
```

see the [guidelines](https://github.com/cosmos/ibc-go/blob/main/docs/dev/pull-requests.md#commit-messages) for commit messages. (view raw markdown for examples)

---

Before we can merge this PR, please make sure that all the following items have been
checked off. If any of the checklist items are not applicable, please leave them but
write a little note why.

- [ ] Targeted PR against correct branch (see [CONTRIBUTING.md](https://github.com/cosmos/ibc-go/blob/main/docs/dev/pull-requests.md#pull-request-targeting)).
- [ ] Linked to Github issue with discussion and accepted design OR link to spec that describes this work.
- [ ] Code follows the [module structure standards](https://github.com/cosmos/cosmos-sdk/blob/main/docs/docs/building-modules/11-structure.md) and [Go style guide](../docs/dev/go-style-guide.md).
- [ ] Wrote unit and integration [tests](https://github.com/cosmos/ibc-go/blob/main/testing/README.md#ibc-testing-package).
- [ ] Updated relevant documentation (`docs/`) or specification (`x/<module>/spec/`).
- [ ] Added relevant `godoc` [comments](https://blog.golang.org/godoc-documenting-go-code).
- [ ] Provide a [commit message](https://github.com/cosmos/ibc-go/blob/main/docs/dev/pull-requests.md#commit-messages) to be used for the changelog entry in the PR description for review.
- [ ] Re-reviewed `Files changed` in the Github PR explorer.
- [ ] Review `Codecov Report` in the comment section below once CI passes.

2023-05-16 10:58 UTC, crodriguezvega commented on modules/light-clients/08-wasm/types/client_state.go
> +		return output, sdkerrors.Wrapf(errors.New(output.Error()), "error occurred while calling contract with code ID %s", hex.EncodeToString(cs.CodeId))
I added the hex encoding of the code ID, so that it's a bit more readable. :)

2023-05-16 10:58 UTC, crodriguezvega commented on modules/light-clients/08-wasm/types/consensus_state_test.go
> +func (suite *TypesTestSuite) TestConsensusStateValidateBasic() {
Renamed the type to follow the existing convention in ibc-go.

2023-05-16 10:58 UTC, crodriguezvega commented on modules/light-clients/08-wasm/types/validation.go
> +	// TODO: is this needed? Tests seem to fail when is check is active
Looks like performing this check makes the test fail. Do we need it or needs to be adapted?

2023-05-16 11:05 UTC, crodriguezvega commented on testing/config.go
> -func NewTendermintConfig(wasm bool) *TendermintConfig {
This is an API breaking change, so we will probably need to handle this differently when we do the backport to v7.2.x

2023-05-16 11:07 UTC, crodriguezvega commented on modules/light-clients/08-wasm/test_data/genesis.json
> +              "code_id": "FrOrNYQLE9a8AWwO57QzGsyGD5Azg9Sd5pi1VLi+mMo=",
I think this code ID was wrong, but I did this a few weeks ago before my holidays and I don't remember the details now... 😁

2023-05-17 00:49 UTC, misko9 commented on testing/config.go
> -func NewTendermintConfig(wasm bool) *TendermintConfig {
Can you elaborate on what this change will break? Is NewTendermintConfig() used directly somewhere that I'm not aware of? The changes to support wasm clients were made to avoid breaking any of the much heavier used APIs such as Coordinator, Endpoint, and TestChain. I can further look into it too if I better understand what breaks.

2023-05-17 01:02 UTC, misko9 commented on modules/light-clients/08-wasm/test_data/genesis.json
> +              "code_id": "FrOrNYQLE9a8AWwO57QzGsyGD5Azg9Sd5pi1VLi+mMo=",
Yeah... probably, the previous SetupWithChannel() code would update the client state's code_id at runtime so the genesis file did not need to be updated (easier earlier in dev), so it was most likely stale. I'll confirm this change now that the contract is stable.

2023-05-17 01:16 UTC, misko9 commented on modules/light-clients/08-wasm/types/validation.go
> +	// TODO: is this needed? Tests seem to fail when is check is active
This is most likely due to the gzip support for uploading / store code. We could check that either the wasm or gzip identifier is present, but I don't think it is necessary. The contract will be stored via a proposal and the wasm vm will easily catch an invalid binary (it's caught me plenty of times :) ). The same gas would have already been spent for the proposal and the cli wouldn't have been used/caught it either in the expected flow.

2023-05-17 20:26 UTC, misko9 requested changes

2023-05-17 20:26 UTC, misko9 commented on modules/light-clients/08-wasm/types/types_test.go
>  	ibctesting.DefaultTestingAppInit = ibctesting.SetupTestingApp
Recommend removing this line and adding it to the suite's SetupTest() method so DefaultTestingAppInit is reset on each test, then only SetupWasmGrandpaWithChannel() changes it when that method is called. Currently, I believe the only reason the SetupWasmGrandpa() call in the respective block of tests is working properly is because SetupWasmTendermint() resets it to the default (i.e. this line) and the execution order alternates between tendermint and grandpa blocks of tests. If additional tests are added for grandpa that uses SetupWasmGrandpa() immediately after a SetupWasmGrandpaWithChannel(), it is difficult to debug and confusing why the genesis test file is still pulled in.

2023-05-17 20:49 UTC, misko9 commented on modules/light-clients/08-wasm/types/types_test.go
>  	ibctesting.DefaultTestingAppInit = ibctesting.SetupTestingApp
You can check this behavior by changing the method name: TestInitializeGrandpa() -> TestStatusGrandpa2() and then re-run suite.

2023-05-22 20:26 UTC, crodriguezvega commented on modules/light-clients/08-wasm/types/validation.go
> +	// TODO: is this needed? Tests seem to fail when is check is active
I will remove this then.

2023-05-22 20:33 UTC, crodriguezvega commented on testing/config.go
> -func NewTendermintConfig(wasm bool) *TendermintConfig {
I tend to consider changes in the signature of any exported function as API-breaking changes, but this might be a bit too strict. :) Maybe it's ok, so we can wait for now to see what the rest of the team thinks.

2023-05-22 20:34 UTC, crodriguezvega commented on modules/light-clients/08-wasm/types/types_test.go
>  	ibctesting.DefaultTestingAppInit = ibctesting.SetupTestingApp
Sorry, I think I don't understand the change that you propose. Is it to add a `SetupTest` function to the suite and do `ibctesting.DefaultTestingAppInit = ibctesting.SetupTestingApp` in that function and then call it in the test cases to reset at the beginning of every test?

2023-05-26 09:36 UTC, crodriguezvega commented on modules/light-clients/08-wasm/types/types_test.go
>  	ibctesting.DefaultTestingAppInit = ibctesting.SetupTestingApp
Thanks for the clarification, @misko9. I just pushed this change.

2023-05-26 13:59 UTC, merged