refactor: localhost verification in 04-channel
strangelove-ventures/ibc-go pull request #7
Opened 2022-10-24 19:46 UTC by jtieri

## Description

closes: #XXXX

---

Before we can merge this PR, please make sure that all the following items have been
checked off. If any of the checklist items are not applicable, please leave them but
write a little note why.

- [ ] Targeted PR against correct branch (see [CONTRIBUTING.md](https://github.com/cosmos/ibc-go/blob/master/CONTRIBUTING.md#pr-targeting))
- [ ] Linked to Github issue with discussion and accepted design OR link to spec that describes this work.
- [ ] Code follows the [module structure standards](https://github.com/cosmos/cosmos-sdk/blob/master/docs/building-modules/structure.md).
- [ ] Wrote unit and integration [tests](https://github.com/cosmos/ibc-go/blob/master/CONTRIBUTING.md#testing)
- [ ] Updated relevant documentation (`docs/`) or specification (`x/<module>/spec/`)
- [ ] Added relevant `godoc` [comments](https://blog.golang.org/godoc-documenting-go-code).
- [ ] Added a relevant changelog entry to the `Unreleased` section in `CHANGELOG.md`
- [ ] Re-reviewed `Files changed` in the Github PR explorer
- [ ] Review `Codecov Report` in the comment section below once CI passes

2022-10-26 16:06 UTC, AdityaSripal commented on modules/core/04-channel/keeper/handshake_test.go
> +				// check if order is supported by channel to determine expected behaviour
Why is this here? The Localhost should automatically support all implemented order features

2022-10-26 16:06 UTC, AdityaSripal commented on modules/core/04-channel/keeper/handshake_test.go
> +		features []string
Seems like we can just remove this

2022-10-26 16:10 UTC, AdityaSripal commented on modules/core/04-channel/keeper/handshake_test.go
> +			path.SetChannelOrdered()
Why are you testing just ORDERED here? Would be good to have two success cases. One with ORDERED and one with UNORDERED

2022-10-26 16:12 UTC, AdityaSripal commented on modules/core/04-channel/keeper/handshake_test.go
> +		{"success with empty stored counterparty channel ID", func() {
I don't understand why this would pass

2022-10-26 16:14 UTC, AdityaSripal commented on modules/core/04-channel/keeper/handshake_test.go
> +			if counterpartyChannelID == "" {
This seems to be causing the above test to pass? But i don't understand what this is testing and why

2022-10-26 16:15 UTC, AdityaSripal commented on modules/core/04-channel/keeper/packet.go
> +const LocalhostID = "connection-localhost"
This seems like something to put in a types package. Maybe `connection/types`?

2022-10-26 16:20 UTC, AdityaSripal commented on modules/core/04-channel/keeper/packet.go
> +		packetCommitment = types.CommitPacket(k.cdc, packet)
Seems like we should be checking commitments are equal before going through acknowledgement verification no?

2022-10-26 16:20 UTC, AdityaSripal commented on modules/core/04-channel/keeper/packet.go
> +		packetCommitment = types.CommitPacket(k.cdc, packet)
The goal is to do all simple checks before expensive proof verification

2022-10-26 19:40 UTC, jtieri commented on modules/core/04-channel/keeper/handshake_test.go
> +				// check if order is supported by channel to determine expected behaviour
Agreed. I was trying to emulate the same testing scenarios and logic as the counterparty test cases so just copied this in because I wasn't quite sure what this was even achieving.

2022-10-26 19:43 UTC, jtieri commented on modules/core/04-channel/keeper/handshake_test.go
> +			path.SetChannelOrdered()
I was mirroring the same test cases in the localhost tests that I saw in the counterparty tests. I'll update this with a success case for both channel order types!

2022-10-26 19:48 UTC, jtieri commented on modules/core/04-channel/keeper/handshake_test.go
> +		{"success with empty stored counterparty channel ID", func() {
This is another case of me trying to mirror the counterparty test cases in the localhost test cases. When I was removing test cases that clearly didn't make sense I wasn't sure why this one passed on the counterparty so I just chucked it in here and figured I would seek clarity later.

2022-10-26 19:52 UTC, jtieri commented on modules/core/04-channel/keeper/packet.go
> +const LocalhostID = "connection-localhost"
Makes sense to me, I wasn't sure if there was anywhere particular you guys would want this so I just punted on it. I'm going to move it into `connection.go` inside `03-connection/types`

2022-10-26 19:52 UTC, jtieri commented on modules/core/04-channel/keeper/handshake_test.go
> +			if counterpartyChannelID == "" {
Good catch, this isn't needed for the localhost tests I just forgot to remove it.

2022-10-26 20:06 UTC, jtieri commented on modules/core/04-channel/keeper/packet.go
> +		packetCommitment = types.CommitPacket(k.cdc, packet)
That definitely makes sense! I was trying to limit the amount of code that needed to be included in each branch of the if-else statement and didn't consider the costs of verifying the proof if it's not necessary. 

I'll make sure the check is performed before proof verification and also start thinking about abstracting both the localhost and counterparty verification as you mentioned in the top level comment.

2022-10-26 20:53 UTC, jtieri commented
Thanks for the feedback here, very helpful! 

I'll make changes to account for your review and also consider how to abstract the verification so that we can dry up the code a bit and make it more readable/maintainable.

I think it should be feasible to create one helper function for channel state verification but I think for packet and timeout verification we may end up needing one verification function per packet type and then separate verification functions for `TimeoutPacket` and `TimeoutOnClose`

2022-10-27 14:07 UTC, AdityaSripal commented on modules/core/04-channel/keeper/handshake_test.go
> +				// check if order is supported by channel to determine expected behaviour
Cool looks like there can be some improvements to the regular handshake tests!

2022-11-10 17:09 UTC, AdityaSripal requested changes
Great work @jtieri ! My main request is to get rid of the channel opts struct and simplify the verifyChannelState function.

2022-11-10 17:09 UTC, AdityaSripal commented on modules/core/04-channel/keeper/handshake.go
> +	if connectionHops[0] != connectiontypes.LocalhostID {
can we abstract this out to a helper function as well just for consistency? `validateChanOpenInit`?

2022-11-10 17:10 UTC, AdityaSripal commented on modules/core/04-channel/keeper/verify.go
> +		if !timeoutHeight.IsZero() && latestHeight >= timeoutHeight.GetRevisionHeight() {
On second thought, let's leave as-is for now

2022-11-10 22:11 UTC, jtieri commented on modules/core/04-channel/keeper/packet.go
> +	err := k.verifyPacketSend(ctx, channel.ConnectionHops[0], packet)
That makes sense to me, will adjust this.

2022-11-10 22:18 UTC, jtieri commented on modules/core/04-channel/keeper/verify.go
> +	opts channelStateOpts,
I agree, I tried this initially but was having some trouble getting the non-localhost tests passing. 

Going back at it today I see that the issue I was running into was because I wasn't overriding the counterparty hops correctly inside of the counterparty verification logic in these parts https://github.com/cosmos/ibc-go/blob/c912fd9d1be3a13470c217d21af40f4a67c230c3/modules/core/04-channel/keeper/handshake.go#L149-L157

2022-11-10 22:19 UTC, jtieri commented on modules/core/04-channel/keeper/handshake.go
> +	if connectionHops[0] != connectiontypes.LocalhostID {
Yeah no problem!

2022-11-10 22:23 UTC, jtieri commented on modules/core/04-channel/keeper/verify.go
> +	opts channelStateOpts,
We will still need to pass in the counterparty port and channel id but it still cleans up much nicer than having a bunch of fields crammed in the opts struct.

2022-11-14 19:27 UTC, AdityaSripal requested changes
Thanks @jtieri ! The handshake, packet, and timeout files look so much cleaner.

I did a very thorough review this time hence the many comments.

Main bugs I found were in `verifyChannel` and you do not have an equivalent `validateChanCloseInit` for localhost. So at the moment, we will fail if you call ChanCloseInit with the localhost connection: https://github.com/cosmos/ibc-go/blob/v5.0.0/modules/core/04-channel/keeper/handshake.go#L399

There are other requests for further cleanup and test issues.

Thanks for all the hard work!

2022-11-14 19:27 UTC, AdityaSripal commented on modules/core/04-channel/keeper/verify.go
> +		latestHeight := uint64(ctx.BlockHeight())
You can use `clienttypes.GetSelfHeight` to compare against timeoutHeight directly:

https://github.com/cosmos/ibc-go/blob/v5.0.0/modules/core/02-client/types/height.go#L186

2022-11-14 19:27 UTC, AdityaSripal commented on modules/core/04-channel/keeper/verify.go
> +	}
These lines seem like they can be pulled back into timeout.go

2022-11-14 19:27 UTC, AdityaSripal commented on modules/core/04-channel/keeper/verify.go
> +		if (timeoutHeight.IsZero() || uint64(ctx.BlockHeight()) < timeoutHeight.GetRevisionHeight()) &&
ditto using GetSelfHeight and comparing directly

2022-11-14 19:27 UTC, AdityaSripal commented on modules/core/04-channel/keeper/verify.go
> +		}
ditto, can DRY by moving this back to timeout.go

2022-11-14 19:27 UTC, AdityaSripal commented on modules/core/04-channel/keeper/verify.go
> +				return sdkerrors.Wrap(types.ErrAcknowledgementExists, "failed localhost packet receipt absence verification")
You should be returning `types.ErrPacketReceived`.

Acknowledgement doesn't necessarily exist

2022-11-14 19:27 UTC, AdityaSripal commented on modules/core/04-channel/keeper/verify.go
> +	}
move this back to timeout.go

2022-11-14 19:27 UTC, AdityaSripal commented on modules/core/04-channel/keeper/verify.go
> +		}
ditto

2022-11-14 19:27 UTC, AdityaSripal commented on modules/core/04-channel/keeper/verify.go
> +				return sdkerrors.Wrapf(types.ErrAcknowledgementExists, "failed localhost packet receipt absence verification")
ditto incorrect error type

2022-11-14 19:27 UTC, AdityaSripal commented on testing/coordinator.go
> +	"github.com/cosmos/ibc-go/v5/modules/core/03-connection/types"
nit: could you name this connectiontypes?

2022-11-14 19:27 UTC, AdityaSripal commented on modules/core/04-channel/keeper/timeout_test.go
> +			expError = types.ErrAcknowledgementExists
This is because you are returning the wrong error type in the localhost verification case. see below

2022-11-14 19:28 UTC, AdityaSripal commented on modules/core/04-channel/keeper/handshake_test.go
> +				suite.chainB.GetContext(), types.ORDERED, []string{path.EndpointB.ConnectionID},
It doesn't because of the verifyChannel bug

2022-11-14 19:30 UTC, AdityaSripal commented on modules/core/04-channel/keeper/handshake_test.go
> +				suite.chainB.GetContext(), types.ORDERED, []string{path.EndpointB.ConnectionID},
Maybe we should rename from `verifyChannelState` to `verifyChannelEnd` or `verifyChannel` for clarity

2022-11-22 20:11 UTC, jtieri commented on modules/core/04-channel/keeper/handshake_test.go
> +			err = path.EndpointB.LocalhostChanOpenTry()
That seems like a valid concern. We wanted to ensure that `ChanOpenTry` was generating unique channel ids for both ends in the localhost case. 

We could move a check down into the block where the test cases are actually run like this:

```
if path.EndpointA.ChannelID != "" {
    suite.Require().NotEqual(path.EndpointA.ChannelID, path.EndpointB.ChannelID)
}
```

that would make the assertion for every case besides for the test case checking that channel verification fails

2022-11-22 20:13 UTC, jtieri commented on modules/core/04-channel/keeper/handshake_test.go
> +			suite.Require().NotEqual(path.EndpointA.ChannelID, path.EndpointB.ChannelID)
Ahh right we only want to make this assertion for test cases that are expected to pass. Yepp i'll make this adjustment, disregard my last comment.

2022-11-22 20:21 UTC, jtieri commented on modules/core/04-channel/keeper/verify.go
> +	channelID string,
no problem, i'll adjust this

2022-11-22 20:27 UTC, jtieri commented on modules/core/04-channel/keeper/verify.go
> +		if actualChannel.State != expectedChannel.State {
Good catch!

2022-11-22 20:30 UTC, jtieri commented on modules/core/04-channel/keeper/verify.go
> +		latestTimestamp, err := k.connectionKeeper.GetTimestampAtHeight(ctx, connectionEnd, latestHeight)
Hmm interesting, I branched off main in our forked repo and yeah looks like it's pretty stale. I'll add this check in here

2022-11-22 21:21 UTC, jtieri commented on modules/core/04-channel/keeper/verify.go
> +		latestTimestamp, err := k.connectionKeeper.GetTimestampAtHeight(ctx, connectionEnd, latestHeight)
Okay so looks like the exact commit I branched off is 80ea89a356da6606b351f0e00fc82786a5c13fad
I no longer see this special case on main and adding it into this branch breaks this test case https://github.com/cosmos/ibc-go/blob/bbac2b1879f009318ad146b099de69ea24cf92b9/modules/core/04-channel/keeper/packet_test.go#L166 presumably because the check on the timestamp is never done

2022-11-22 21:46 UTC, jtieri commented on modules/core/04-channel/keeper/verify.go
> +		}
Good call. 

I forgot why I opted into having this in the `verifyTimeoutPacket` call but now that i adjusted it and ran the tests i remember it was because it was breaking a test case that was expecting the connection does not exist error, went ahead and pulled this back into `timeout.go` and adjusted the test case as necessary

2022-11-22 22:04 UTC, jtieri commented on modules/core/04-channel/keeper/handshake_test.go
> +				suite.chainB.GetContext(), types.ORDERED, []string{path.EndpointB.ConnectionID},
Good catch! I fixed the bug and renamed to `verifyChannelEnd`

2022-11-22 22:13 UTC, jtieri commented on modules/core/04-channel/keeper/packet_test.go
> +					suite.Require().Equal(string([]byte{byte(1)}), receipt, "packet receipt is not empty string")
I'll change to `packet receipt in store does not match expected packet receipt value`=

2022-11-22 23:22 UTC, jtieri commented on modules/core/04-channel/keeper/handshake_test.go
> +		{"channel state is not INIT", func() {
I added a test case for `ChanOpenTry` `ChanOpenAck` `ChanOpenConfirm` & `ChanCloseConfirm` that overrides the expected channels version so that the deep equality check should fail.

2022-11-22 23:29 UTC, jtieri commented
I'm happy to help on this @AdityaSripal! 

I went ahead and handled most of your suggestions including adding the `validateChanCloseInit` helper function as well as adding some test cases that ensure that `verifyChannelEnd` bug is caught on the deep equality check for the expected vs. actual channel. The only thing I didn't change was adding the special case for solomachine timestamp handling, see comment above.

2022-11-28 13:37 UTC, colin-axner reviewed
Starting to review these changes. Since there are a lot of diffs, it'll take me a bit to formulate my suggestions

2022-11-28 13:37 UTC, colin-axner commented on modules/core/04-channel/keeper/handshake.go
> +		ConnectionHops: connectionHops,
Verified with the following diff:
```diff
@@ -76,7 +76,7 @@ func (suite *TransferTestSuite) TestHandleMsgTransfer() {
        // NOTE:
        // pathBtoC.EndpointA = endpoint on chainB
        // pathBtoC.EndpointB = endpoint on chainC
-       pathBtoC := NewTransferPath(suite.chainB, suite.chainC)
+       pathBtoC := NewTransferPath(suite.chainC, suite.chainB)
```

We need to add test cases to cover this. Note I believe ConnOpenAck is correct (haven't fully verified)

2022-11-28 14:00 UTC, colin-axner commented on modules/core/04-channel/keeper/handshake.go
> +		ConnectionHops: connectionHops,
I understand now. The expected channel being constructed here is being modified in `verifyChannelEnd` to update to the correct values. I would recommend not using `expectedChannel` to check the channel end on the executing chain. The `expectedChannel` should only be associated/used with the counterparty chain

2022-11-28 16:58 UTC, colin-axner commented
I like the usage of `validate` and `verify`, but I think a couple more adjustments are needed. 

Currently you are making two design decisions:
- within a call stack, only perform an if statement on the connectionID once 
- split validation and verification logic

In general I agree with both decisions, but currently in order to fulfill the first, you are conflating validation and verification logic. That is `verifyChannelEnd` is also validating that channel order is supported by the referenced channel end. 

What do we need to validate that the localhost doesn't need to validate? Any connection related parameters, that is, fields of a connection end which we must account for in handshakes or packet handling, such as connection version, client status, etc. 

I propose the following structure:
```go
func handler() {
    // shared validation
    // both localhost and normal connection must perform these checks
    
    // generation of expected value
    
    if connectionID.IsLocalhost() {
        if err := verifyChannelOnLocalhost(); err != nil {
            return err
        }
        
    } else {
        connectionEnd, found := k.connectionKeeper.GetConnection(ctx, connectionID)
        if !found {
            return err
        }
        
        if err := k.validateConnectionOnChanOpenTry(connectionEnd); err != nil {
        }
        }

2022-11-28 17:04 UTC, AdityaSripal approved these changes
Thanks @jtieri for responding quickly to the multiple rounds of reviews. Everything looks good to me now. Leaving some final nits

2022-11-28 17:04 UTC, AdityaSripal commented on modules/core/04-channel/keeper/handshake.go
> +		ConnectionHops: connectionHops,
I agree that the connectionHops changing internally in `verifyChannelEnd` is confusing tho.

My nit suggestion here is to leave the connectionHops blank in the expectedChannel, and pass in the `connectionID` as an additional argument to `verifyChannelEnd`. Then inside `verifyChannelEnd`, we fill in `connectionHops` on the expectedChannel depending on the value of connectionID.

Either way this should be clearly documented

2022-11-28 17:11 UTC, colin-axner commented on modules/core/04-channel/keeper/handshake.go
> +		ConnectionHops: connectionHops,
https://github.com/strangelove-ventures/ibc-go/pull/7#issuecomment-1329434327 This is my recommendation

2022-11-28 17:13 UTC, colin-axner commented on modules/core/04-channel/keeper/verify.go
> +		latestTimestamp, err := k.connectionKeeper.GetTimestampAtHeight(ctx, connectionEnd, latestHeight)
The check is needed for pre v7 versions. The change in the client state interface fixed this issue

2022-11-28 18:04 UTC, AdityaSripal commented
Are you suggesting to have the `if-else` clause inside the individual handshake and packet functions @colin-axner ?

2022-12-01 22:01 UTC, jtieri commented on modules/core/04-channel/keeper/handshake.go
> +		ConnectionHops: connectionHops,
Regarding the connectionHops, that totally makes sense and I will go ahead and get that sorted out.

As for @colin-axner's other suggestion re: verification vs. validation separations, I'm not strongly opinionated here and seeing as this ultimately falls into being maintained by the IBC team long term I'm happy to make whatever adjustments are preferred on your guys end.

2022-12-05 17:59 UTC, colin-axner commented
Feel free to ignore my suggestions for now since they are more looking at integration into ibc-go as opposed to correctness on this fork. I'll be going on an extended vacation soon so I was asked to read over these changes now so the team has an idea of my recommendations before I go offline

2023-01-30 20:55 UTC, jtieri commented
Closing this PR, IBC team is moving forward with IBC loopback based off of cosmos/ibc-go#2700 in [feature branch 09-localhost](https://github.com/cosmos/ibc-go/tree/09-localhost)

2023-01-30 20:55 UTC, closed without merging